### ISSUE TITLE
Docker Containers only getting port numbers

### ISSUE THREAD

**Issue by CCS4Hosting** [CCS4Hosting/Project-Hosting#3]
Currently Docker containers are not getting IPs, only port numbers.

Something went wrong

**Comment by Alex-Coulon** [comment]
Thanks for flagging, looks like we had a merging issue. We'll prioritise this.

**Comment by Alex-Coulon** [comment]
UPDATE: Issue had been found, should be a quick fix. Will keep y'all updated.

**Comment by Alex-Coulon** [comment]
UPDATE: We're fast. When pushing the new dashboard a variable was forgotten. We have fixed the issue and tested it. I've flagged this to the front-end team to try to avoid these problems.

Thanks for flagging!
